package pharmacy.entities;

import custom.orm.db.utils.annotations.*;

@Entity(tableName = "age_group")
public class AgeGroup {

    @Id
    @AutoGenerated
    private int id;

    @Column(name = "name")
    private String name;

    public AgeGroup() {
    }

    public AgeGroup(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return "AgeGroup [id=" + id + ", name=" + name + "]";
    }
}