package pharmacy.entities;

import custom.orm.db.utils.annotations.*;

@Entity(tableName = "pharmacy_client")
public class Client {

    @Id
    @AutoGenerated
    private int id;

    @Column(name = "name")
    private String name;

    public Client() {
    }

    public Client(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return "Client [id=" + id + ", name=" + name + "]";
    }
}