package pharmacy.entities;

import custom.orm.db.utils.annotations.AutoGenerated;
import custom.orm.db.utils.annotations.Column;
import custom.orm.db.utils.annotations.Entity;
import custom.orm.db.utils.annotations.Id;

@Entity(tableName = "employees")
public class Employee {
    @Id
    @AutoGenerated
    int id;

    @Column(name = "emp_name")
    String name;

    public Employee(int id) {
        this.id = id;
    }

    public Employee() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
