package pharmacy.entities;

import custom.orm.db.utils.annotations.AutoGenerated;
import custom.orm.db.utils.annotations.Entity;
import custom.orm.db.utils.annotations.Id;

@Entity(tableName = "genders")
public class Gender {
    @Id
    @AutoGenerated
    int id;

    String name;

    public Gender(int id) {
        this.id = id;
    }

    public Gender() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
