package pharmacy.entities;

import java.sql.Date;

import custom.orm.db.utils.annotations.*;
import pharmacy.services.MedicineDosageService;

@Entity(tableName = "histo_price_med")
public class HistoPrice {
    @Id
    @AutoGenerated
    int id;

    @Column(name = "med_dosage_id")
    int medDosageId;

    @NotMapped
    MedicinesDosage dosage;

    @Column(name = "date_start")
    Date datePrice;

    double price;

    public HistoPrice(int medDosageId, Date datePrice, double price) {
        this.medDosageId = medDosageId;
        this.datePrice = datePrice;
        this.price = price;
    }

    public HistoPrice() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getMedDosageId() {
        return medDosageId;
    }

    public void setMedDosageId(int medDosageId) throws Exception {
        this.medDosageId = medDosageId;
        
        MedicineDosageService medicineDosageService = new MedicineDosageService();
        this.setDosage(medicineDosageService.findById(medDosageId));
    }

    public MedicinesDosage getDosage() {
        return dosage;
    }

    public void setDosage(MedicinesDosage dosage) {
        this.dosage = dosage;
    }

    public Date getDatePrice() {
        return datePrice;
    }

    public void setDatePrice(Date datePrice) {
        this.datePrice = datePrice;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }
}
