package pharmacy.entities;

import custom.orm.db.utils.annotations.*;

@Entity(tableName = "laboratories")
public class Laboratory {
    @Id
    @AutoGenerated
    int id;

    String name;

    @Column(name = "type_id")
    int typeId;

    @NotMapped
    LabType labType;

    public Laboratory(int id, String name, int typeId) {
        this.id = id;
        this.name = name;
        this.typeId = typeId;
    }

    public Laboratory(String name, int typeId) {
        this.name = name;
        this.typeId = typeId;
    }

    public Laboratory() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getTypeId() {
        return typeId;
    }

    public void setTypeId(int typeId) {
        this.typeId = typeId;
    }

    public LabType getLabType() {
        return labType;
    }

    public void setLabType(LabType labType) {
        this.labType = labType;
    }
}
