package pharmacy.entities;

import custom.orm.db.QueryManager;
import custom.orm.db.utils.annotations.*;

@Entity(tableName = "laboratories")
public class Laboratory {

    @Id
    @AutoGenerated
    int id;

    String name;

    @Column(name = "type_id")
    int typeId;

    @NotMapped
    LabType labType;

    public Laboratory(int id) {
        this.id = id;
    }

    public Laboratory(int id, String name, int typeId) {
        this.id = id;
        this.name = name;
        this.typeId = typeId;
    }

    public Laboratory(String name, int typeId) {
        this.name = name;
        this.typeId = typeId;
    }

    public Laboratory() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getTypeId() {
        return typeId;
    }

    public void setTypeId(int typeId) throws Exception {
        this.typeId = typeId;

        QueryManager qm = new QueryManager();
        Object labObj = qm.findById(null, new LabType(typeId, ""));

        if (labObj != null) {
            this.setLabType((LabType) labObj);
        } else {
            this.setLabType(null);
        }
    }

    public LabType getLabType() {
        return labType;
    }

    public void setLabType(LabType labType) {
        this.labType = labType;
    }
}
