package pharmacy.entities;

import custom.orm.db.utils.annotations.*;

@Entity(tableName = "med_form")
public class MedForm {

    @Id
    @AutoGenerated
    int id;

    String name;

    public MedForm(String name) {
        this.name = name;
    }

    public MedForm(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public MedForm() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
