package pharmacy.entities;

import custom.orm.db.utils.annotations.*;

@Entity(tableName = "medical_constraints")
public class MedicalConstraint {
    @Id
    @AutoGenerated
    int id;

    String name;

    public MedicalConstraint(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public MedicalConstraint(String name) {
        this.name = name;
    }

    public MedicalConstraint() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
