package pharmacy.entities;

import custom.orm.db.utils.annotations.*;

@Entity(tableName = "medicines_dosages")
public class MedicinesDosage {
    @Id
    @AutoGenerated
    int id;

    @Column(name = "med_format_id")
    int medFormatId;

    double price;

    double dose;

    @Column(name = "unit_id")
    int unitId;

    public MedicinesDosage(int medFormatId, double price, double dose, int unitId) {
        this.medFormatId = medFormatId;
        this.price = price;
        this.dose = dose;
        this.unitId = unitId;
    }

    public MedicinesDosage() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getMedFormatId() {
        return medFormatId;
    }

    public void setMedFormatId(int medFormatId) {
        this.medFormatId = medFormatId;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public double getDose() {
        return dose;
    }

    public void setDose(double dose) {
        this.dose = dose;
    }

    public int getUnitId() {
        return unitId;
    }

    public void setUnitId(int unitId) {
        this.unitId = unitId;
    }
}
