package pharmacy.entities;

import custom.orm.db.utils.annotations.AutoGenerated;
import custom.orm.db.utils.annotations.Column;
import custom.orm.db.utils.annotations.Entity;
import custom.orm.db.utils.annotations.Id;

@Entity(tableName = "medicines_restrictions")
public class MedicinesRestriction {

    @Id
    @AutoGenerated
    int id;

    @Column(name = "med_id")
    int medId;

    @Column(name = "constraint_id")
    int constraintId;

    public MedicinesRestriction(int medId, int constraintId) {
        this.medId = medId;
        this.constraintId = constraintId;
    }

    public MedicinesRestriction() {
    }

    public MedicinesRestriction(int id, int medId, int constraintId) {
        this.id = id;
        this.medId = medId;
        this.constraintId = constraintId;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getMedId() {
        return medId;
    }

    public void setMedId(int medId) {
        this.medId = medId;
    }

    public int getConstraintId() {
        return constraintId;
    }

    public void setConstraintId(int constraintId) {
        this.constraintId = constraintId;
    }
}
