package pharmacy.entities;

import java.time.LocalDateTime;

import custom.orm.db.utils.annotations.*;

@Entity(tableName = "medicines_transactions")
public class MedicineTransaction {
    @Id
    @AutoGenerated
    int id;

    @Column(name = "med_dosage_id")
    int medDosageId;

    @NotMapped
    MedicinesDosage medDosage;

    @Column(name = "transaction_date")
    LocalDateTime transactionDate;

    @Column(name = "in_value")
    int inValue;

    @Column(name = "out_value")
    int outValue;

    double price;

    public MedicineTransaction(int medDosageId, LocalDateTime transactionDate, int inValue, int outValue,
            double price) {
        this.medDosageId = medDosageId;
        this.transactionDate = transactionDate;
        this.inValue = inValue;
        this.outValue = outValue;
        this.price = price;
    }

    public MedicineTransaction() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getMedDosageId() {
        return medDosageId;
    }

    public void setMedDosageId(int medDosageId) {
        this.medDosageId = medDosageId;
    }

    public MedicinesDosage getMedDosage() {
        return medDosage;
    }

    public void setMedDosage(MedicinesDosage medDosage) {
        this.medDosage = medDosage;
    }

    public LocalDateTime getTransactionDate() {
        return transactionDate;
    }

    public void setTransactionDate(LocalDateTime transactionDate) {
        this.transactionDate = transactionDate;
    }

    public int getInValue() {
        return inValue;
    }

    public void setInValue(int inValue) {
        this.inValue = inValue;
    }

    public int getOutValue() {
        return outValue;
    }

    public void setOutValue(int outValue) {
        this.outValue = outValue;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }
}
