package pharmacy.entities;

import custom.orm.db.QueryManager;
import custom.orm.db.utils.annotations.*;

@Entity(tableName = "medicines_formats")
public class MedicinesFormat {

    @Id
    @AutoGenerated
    int id;

    @Column(name = "med_id")
    int medId;

    @Column(name = "form_id")
    int formId;

    @NotMapped
    MedForm medForm;

    public MedicinesFormat(int medId, int formId) {
        this.medId = medId;
        this.formId = formId;
    }

    public MedicinesFormat() {
    }

    public MedForm getMedForm() {
        return medForm;
    }

    public void setMedForm(MedForm medForm) {
        this.medForm = medForm;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getMedId() {
        return medId;
    }

    public void setMedId(int medId) {
        this.medId = medId;
    }

    public int getFormId() {
        return formId;
    }

    public void setFormId(int formId) throws Exception {
        this.formId = formId;

        QueryManager qm = new QueryManager();
        this.setMedForm((MedForm) qm.findById(null, new MedForm(formId)));
    }

    @Override
    public String toString() {
        return "MedicinesFormat [getMedForm()=" + getMedForm() + ", getId()=" + getId() + ", getMedId()=" + getMedId()
                + "]";
    }
}
