package pharmacy.entities;

import java.time.LocalDate;

import custom.orm.db.utils.annotations.*;

@Entity(tableName = "products_of_the_month")
public class ProductMonth {
    @Id
    @AutoGenerated
    int id;

    @Column(name = "id_medicine")
    int idMedicine;

    @Column(name = "date_validity")
    LocalDate dateValidity;

    public ProductMonth(int idMedicine, LocalDate dateValidity) {
        this.idMedicine = idMedicine;
        this.dateValidity = dateValidity;
    }

    public ProductMonth() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getIdMedicine() {
        return idMedicine;
    }

    public void setIdMedicine(int idMedicine) {
        this.idMedicine = idMedicine;
    }

    public LocalDate getDateValidity() {
        return dateValidity;
    }

    public void setDateValidity(LocalDate dateValidity) {
        this.dateValidity = dateValidity;
    }
}
