package pharmacy.entities;

import custom.orm.db.utils.annotations.*;
import pharmacy.services.ClientService;
import pharmacy.services.SalesDetailsService;

import java.util.Date;
import java.util.List;

@Entity(tableName = "sales")
public class Sales {

    @Id
    @AutoGenerated
    private int id;

    @Column(name = "date_sales")
    private Date date;

    @Column(name = "id_client")
    private int clientId;

    private double commission = 5;

    @Column(name = "employee_id")
    private int empId;

    @NotMapped
    private Client client; // Client object not mapped to the database

    @NotMapped // Assuming a OneToMany relationship with SalesDetails
    private List<SalesDetails> details;

    public Sales() throws Exception {
        // this.setDetails(null);
    }

    public Sales(Date date, int clientId) throws Exception {
        // this.setDetails(null);
        this.date = date;
        this.setClientId(clientId);
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public int getClientId() {
        return clientId;
    }

    public double getCommission() {
        return commission;
    }

    public void setCommission(double commission) {
        this.commission = commission;
    }

    public int getEmpId() {
        return empId;
    }

    public void setEmpId(int empId) {
        this.empId = empId;
    }

    public void setClientId(int clientId) throws Exception {
        this.clientId = clientId;
        ClientService cs = new ClientService();
        this.setClient(cs.findById(clientId));
    }

    public Client getClient() {
        return client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    public List<SalesDetails> getDetails() {
        return details;
    }

    public void setDetails(List<SalesDetails> details) throws Exception {
        if (details == null) {
            SalesDetailsService sts = new SalesDetailsService();
            details = sts.getAll(this);
        }
        this.details = details;
    }
}