package pharmacy.entities;

import custom.orm.db.utils.annotations.*;
import pharmacy.services.MedicineDosageService;

@Entity(tableName = "sales_details")
public class SalesDetails {

    @Id
    @AutoGenerated
    private int id;

    @Column(name = "id_sales")
    private int saleId;

    @Column(name = "id_med_dosage")
    private int medDosageId;

    private int quantity;

    @Column(name = "unit_price")
    private double unitPrice;

    @NotMapped
    private MedicinesDosage medDosage; // MedDosage object not mapped to the database

    public SalesDetails() {
    }

    public SalesDetails(int saleId, int medDosageId, int quantity, double unitPrice) {
        this.saleId = saleId;
        this.medDosageId = medDosageId;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getSaleId() {
        return saleId;
    }

    public void setSaleId(int saleId) {
        this.saleId = saleId;
    }

    public int getMedDosageId() {
        return medDosageId;
    }

    public void setMedDosageId(int medDosageId) throws Exception {
        this.medDosageId = medDosageId;

        MedicineDosageService mds = new MedicineDosageService();
        MedicinesDosage medDosage = mds.findById(medDosageId);
        this.setMedDosage(medDosage);
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public double getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(double unitPrice) {
        this.unitPrice = unitPrice;
    }

    public MedicinesDosage getMedDosage() {
        return medDosage;
    }

    public void setMedDosage(MedicinesDosage medDosage) {
        this.medDosage = medDosage;
    }
}